// This file was auto-generated by prisma-generator-typescript-interfaces

export type ChallengeType = "SOLO" | "ADVERSARIAL";

export type ChallengeStatus = "OPEN" | "COMPLETED" | "FAILED";

export type TitleType = "SINGLE_REQUIREMENT" | "MULTI_REQUIREMENT_AVERAGE";

export interface Admin {
  id: number;
  username: string;
  password: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Attribute {
  id: number;
  name: string;
  description: string;
  challenges?: Challenge[];
  entityAttributes?: TitleRequirement[];
  playerAttributeScores?: PlayerAttributeScore[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Player {
  id: number;
  name: string | null;
  playerCode: string;
  challengeParticipation?: ChallengeParticipant[];
  playerAttributeScores?: PlayerAttributeScore[];
  events?: GameEventPlayer[];
  createdAt: Date;
  updatedAt: Date;
}

export interface GameEvent {
  id: number;
  name: string;
  description: string;
  current: boolean;
  players?: GameEventPlayer[];
  challengeInstances?: ChallengeInstance[];
  playerAttributeScores?: PlayerAttributeScore[];
  createdAt: Date;
  updatedAt: Date;
}

export interface GameEventPlayer {
  id: number;
  eventId: number;
  playerId: number;
  event?: GameEvent;
  player?: Player;
  createdAt: Date;
  updatedAt: Date;
}

export interface PlayerAttributeScore {
  id: number;
  playerId: number;
  attributeId: number;
  eventId: number;
  score: number;
  player?: Player;
  attribute?: Attribute;
  event?: GameEvent;
  createdAt: Date;
  updatedAt: Date;
}

export interface Challenge {
  id: number;
  description: string;
  score: number;
  type: ChallengeType;
  custom: boolean;
  attributeId: number;
  attribute?: Attribute;
  instances?: ChallengeInstance[];
  createdAt: Date;
  updatedAt: Date;
}

export interface ChallengeInstance {
  id: number;
  challengeId: number;
  eventId: number;
  challenge?: Challenge;
  event?: GameEvent;
  participants?: ChallengeParticipant[];
  createdAt: Date;
  updatedAt: Date;
}

export interface ChallengeParticipant {
  id: number;
  playerId: number;
  instanceId: number;
  status: ChallengeStatus;
  player?: Player;
  instance?: ChallengeInstance;
  createdAt: Date;
  updatedAt: Date;
}

export interface Title {
  id: number;
  name: string;
  imageUrl: string | null;
  description: string;
  requirements?: TitleRequirement[];
  titleType: TitleType;
  createdAt: Date;
  updatedAt: Date;
}

export interface TitleRequirement {
  id: number;
  titleId: number;
  attributeId: number;
  title?: Title;
  attribute?: Attribute;
  threshold: number;
  createdAt: Date;
  updatedAt: Date;
}
